### ISSUE TITLE
Use `Compact` type to simplify compact encoding examples?

### ISSUE THREAD

**Issue by jsdw** [wentelteefje/parity-scale-codec-page#2]
here, an `AsCompact` type is defined to compact encode things: https://github.com/wentelteefje/parity-scale-codec-page/blob/eeb43ea5be4d57ce4e4fc3f4cb235285bf5fec33/content/encode.md?plain=1#L159

Just a small suggestion would be to `use parity_scale_codec::Compact` instead of `HasCompact` to simplify the code, eg:

```rust
use parity_scale_codec::{Encode, Compact};

fn main() {
    println!("{:02x?}", 69u8.encode());
    println!("{:02x?}", 69u32.encode());
    println!("{:02x?}", Compact(69u8).encode());
    println!("{:02x?}", Compact(69u32).encode());
}
[45]
[45, 00, 00, 00]
[15, 01]
[15, 01]
```

**Comment by wentelteefje** [comment]
Done.
