### ISSUE TITLE
Move `Result` and `Option` as examples of `Enum` in specification?

### ISSUE THREAD

**Issue by jsdw** [wentelteefje/parity-scale-codec-page#3]
Here, `Result` and `Option` are two "top level" cases in the spec:

https://github.com/wentelteefje/parity-scale-codec-page/blob/eeb43ea5be4d57ce4e4fc3f4cb235285bf5fec33/content/specification.md?plain=1#L40

But really they are just specific instances of how enums in general are encoded, so perhaps it would make sense to use these types as examples of enum encoding, rather than have them as top level items in the spec table?

**Comment by wentelteefje** [comment]
While this is technically true, I don't think it would enhance the readability of the specification. Both `Result` and `Option` types are used a lot in Substrate and should therefore be discoverable at a glance. I moved the order of the items to make it more logically sound. It's not a perfect solution though, I agree.
